ratings:
  paths:
    - "src/**/*.js"
exclude_paths:
  - "build"
  - "config"
  - "coverage"
  - "node_modules"
  - "public"
  - "scripts"
  - "src/**/*.dev.{js,jsx,mjs}"
  - "src/initialState.js"
  - "spec"
